//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resources.rc
//
#define IDS_E_CRITICALERROR             1
#define IDS_E_CRITICAL                  1
#define IDS_E_TITLE                     2
#define IDS_E_INIT                      3
#define IDS_E_MODELS                    7
#define IDS_E_INTRO                     8
#define IDS_E_MUSIC                     9
#define IDS_E_INITWINDOW                10
#define IDS_E_DDRAW                     11
#define IDS_E_SETCOOPERATIVELEVEL       12
#define IDS_E_DISPLAYMODE               13
#define IDS_E_PRIMARYSURFACE            14
#define IDS_E_CLIPPER                   15
#define IDS_E_GETBACKBUFFER             16
#define IDS_E_CREATEBACKBUFFER          17
#define IDS_E_NOZBUFFER                 18
#define IDS_E_CREATEZBUFFER             19
#define IDS_E_NOUPDATEAFTERZBUFFER      20
#define IDS_E_D3D                       21
#define IDS_E_NOD3D7                    22
#define IDS_E_CREATEDEVICE              23
#define IDS_E_VIEWPORT                  24
#define IDS_E_DIRECTSOUND               25
#define IDS_E_DSSETCOOPERATIVELEVEL     26
#define IDS_E_PRIMARYBUFFER             27
#define IDS_E_DIRECTINPUT               28
#define IDS_E_LOADSOUNDS                29
#define IDS_E_LOADTEXTURES              30
#define IDS_E_LOADSPRITES               31
#define IDS_E_RESTORETEXTURES           32
#define IDS_T_CLASSNAME                 33
#define IDS_T_TITLESERVER               34
#define IDS_T_TITLECLIENT               35
#define IDS_T_WIREFRAME1                36
#define IDS_T_WIREFRAME2                37
#define IDS_T_WIREFRAME3                38
#define IDS_T_LOADING                   39
#define IDS_T_LOADED0                   40
#define IDS_T_LOADED1                   41
#define IDS_T_LOADED2                   42
#define IDS_T_LOADED3                   43
#define IDS_T_LOADED4                   44
#define IDS_T_LOADED5                   45
#define IDS_T_LOADED6                   46
#define IDS_T_LOADED7                   47
#define IDS_T_LOADED8                   48
#define IDS_T_LOADED9                   49
#define IDS_T_SOUNDON                   50
#define IDS_T_SOUNDOFF                  51
#define IDS_T_MUSICOFF                  52
#define IDS_T_MUSICON                   53
#define IDS_T_SCREENSHOTSAVED           54
#define IDS_T_MOUSEREVERSED             55
#define IDS_T_MOUSENORMAL               56
#define IDS_T_TOT                       57
#define IDS_T_GOLFEND                   58
#define IDS_T_CHICKENHASHIT             59
#define IDS_T_FARMERWASHIT              60
#define IDS_T_HATS0                     61
#define IDS_T_HATS1                     62
#define IDS_T_HATS2                     63
#define IDS_T_HATS3                     64
#define IDS_T_HATS4                     65
#define IDS_T_HATS5                     66
#define IDS_T_HATS6                     67
#define IDS_T_HAT                       68
#define IDS_T_GOTGARTENKRALLE           69
#define IDS_T_GOTGOLFER                 70
#define IDS_T_GOTDRESCHER               71
#define IDS_T_GOTPLASMA                 72
#define IDS_T_GAMENAME                  73
#define IDS_T_INVALIDSIZE               74
#define IDS_T_INVALIDSIZETITLE          75
#define IDS_T_ERRORENUMSESSIONS         76
#define IDS_T_NOSESSIONS                77
#define IDS_T_REFRESH                   78
#define IDS_E_CREATEGAME                79
#define IDS_E_CREATEPLAYER              80
#define IDS_E_JOINGAME                  81
#define IDS_T_JOINED                    82
#define IDS_T_LEFT                      83
#define IDS_T_NEWSERVER                 84
#define IDS_T_NAMECHANGED               85
#define IDS_T_SERVERCHANGEDWORLD        86
#define IDS_T_LOSGEHTS                  87
#define IDS_T_SERVERCAT                 88
#define IDS_T_PLAYERTYPES0              89
#define IDS_T_PLAYERTYPES1              90
#define IDS_T_PLAYER                    91
#define IDS_T_NAME                      92
#define IDS_T_ID                        93
#define IDS_T_KILLS                     94
#define IDS_T_PING                      95
#define IDS_T_TYPE                      96
#define IDS_M_MAINMENU                  97
#define IDS_M_CONTINUE                  98
#define IDS_M_OPTIONS                   99
#define IDS_M_SERVEROPTIONS             100
#define IDS_M_INFO                      101
#define IDR_ICON                        101
#define IDS_M_EXIT                      102
#define IDS_M_BACK                      103
#define IDS_M_FOG                       104
#define IDD_GAMELIST                    104
#define IDS_M_SPECULAR                  105
#define IDD_CONNECTION                  105
#define IDS_M_VSYNC                     106
#define IDD_GAMESETTINGS                106
#define IDS_M_BLOOD                     107
#define IDS_M_FEDERN                    108
#define IDS_M_GIBS                      109
#define IDS_M_BLOODAMOUNT               110
#define IDS_M_SOUND                     111
#define IDS_M_UNREALSOUND               112
#define IDB_OK                          113
#define IDS_M_GACKERN                   113
#define IDB_LOADING                     114
#define IDS_M_MUSIC                     114
#define IDB_LOADINGMASK                 115
#define IDS_M_REVERSEMOUSE              115
#define IDB_OKMASK                      116
#define IDS_M_SMOOTHMOUSE               116
#define IDS_M_MOUSESENSITIVITY          117
#define IDS_M_GOLFERGEBNISSE            118
#define IDS_M_GRAFIK                    119
#define IDS_M_SONSTIGES                 120
#define IDS_M_ALPHABLENDING             121
#define IDS_M_HAUPTIDEE                 122
#define IDS_M_VORSCHLAEGE               123
#define IDS_M_PROGRAMMIERER             124
#define IDS_M_GRAFIKER                  125
#define IDS_M_TEXTUREN                  126
#define IDS_M_SPRITES                   127
#define IDS_M_MODELLE                   128
#define IDS_M_SOUNDS                    129
#define IDS_M_MUSIK                     130
#define IDS_M_NETWORK                   131
#define IDS_M_BETATESTER                132
#define IDS_M_ENDE                      133
#define IDS_M_EMAILS                    134
#define IDS_M_INFOABOUT                 135
#define IDS_M_ANZAHL                    136
#define IDS_M_CHICKEN                   137
#define IDS_M_STAELLE                   138
#define IDS_M_TREES                     139
#define IDS_M_GARTENKRALLEN             140
#define IDS_M_GOLFSCHLAEGER             141
#define IDS_M_DRESCHER                  142
#define IDS_M_PLASMACANNONS             143
#define IDS_M_EINSTELLUNGEN             144
#define IDS_M_AIRCONTROL                145
#define IDS_M_EGGDAMAGE                 146
#define IDS_M_GRAVITY                   147
#define IDS_M_JUMPMULTIPLIER            148
#define IDS_M_PLASMARATE                149
#define IDS_M_PLASMAREGENERATION        150
#define IDS_M_REGENERATEPOWER           151
#define IDS_M_SITSPEED                  152
#define IDS_M_TAKEPOWER                 153
#define IDS_M_THROWTIME                 154
#define IDS_M_KI                        155
#define IDS_C_INTRO1                    156
#define IDS_C_INTRO2                    157
#define IDS_C_SERVERONLY                158
#define IDS_C_NOFLOAT                   159
#define IDS_C_VARCHANGED                160
#define IDS_C_FOGON                     161
#define IDS_C_FOGOFF                    162
#define IDS_C_ALLCOMMANDS               163
#define IDS_C_SPAWNPARAMETER            164
#define IDS_C_SPAWNPARAMETERS0          165
#define IDS_C_SPAWNPARAMETERS1          166
#define IDS_C_SPAWNPARAMETERS2          167
#define IDS_C_SPAWNPARAMETERS3          168
#define IDS_C_SPAWNPARAMETERS4          169
#define IDS_C_SPAWNPARAMETERS5          170
#define IDS_C_SPAWNPARAMETERS6          171
#define IDS_C_SPAWNPARAMETERS7          172
#define IDS_C_SPAWNED                   173
#define IDS_C_INVALIDPARAMETER          174
#define IDS_C_INVALIDUID                176
#define IDS_C_UIDNOTFOUND               177
#define IDS_C_OBJECTREMOVED             178
#define IDS_C_SPECULAROFF               179
#define IDS_C_SPECULARON                180
#define IDS_C_NEWWORLD                  181
#define IDS_C_MESSAGESENT               182
#define IDS_C_INSANEGORELEVEL           183
#define IDS_C_ALPHABLENDINGON           184
#define IDS_C_ALPHABLENDINGOFF          185
#define IDS_C_YOURNAME                  186
#define IDS_C_NAMECHANGED               187
#define IDS_C_NEWRACE                   188
#define IDS_C_PLAYERTYPECHANGED         189
#define IDS_C_INVALIDCOMMAND            190
#define IDS_C_OBJECTINFOS               191
#define IDS_C_OBJECTINFO                192
#define IDS_E_SESSIONLOST               193
#define IDS_M_REFLECTIONS               194
#define IDS_M_CROSSHAIR                 195
#define IDS_T_HATS7                     196
#define IDS_M_PRESSURE                  197
#define IDS_M_RESPAWNTIME               198
#define IDS_E_KICKED                    199
#define IDS_E_KICKEDYOURSELF            200
#define IDS_T_CHICKENWASHIT             201
#define IDS_T_FARMERHASHIT              202
#define IDS_M_RESOLUTION                203
#define IDS_M_APPLY                     204
#define IDS_M_FULLSCREEN                205
#define IDS_M_ANIMATIONS                206
#define IDC_NONE                        206
#define IDS_M_THANKS                    207
#define IDS_M_GRASS                     208
#define IDS_M_SHOWPLAYERNAMES           209
#define IDS_M_PLAYERNAMES               209
#define IDS_C_SPAWNPARAMETERS8          210
#define IDS_M_AI                        211
#define IDS_M_DIRESTRAITS               212
#define IDS_M_FARMER                    213
#define IDS_M_FIRE                      214
#define IDS_M_REVERSEFLIGHT             215
#define IDC_NAME                        1000
#define IDC_SPIELERTYP                  1001
#define IDC_RADIO2                      1002
#define IDC_LIST                        1003
#define IDC_CREATE                      1004
#define IDC_JOIN                        1005
#define IDC_FULLSCREEN                  1006
#define IDC_REFRESH                     1007
#define IDC_RESOLUTION                  1008
#define IDC_GAME                        1009
#define IDC_DEVICE                      1009
#define IDC_DIRECTPLAYPROTOCOL          1010
#define IDC_FARMER                      1011
#define IDC_SPIN4                       1012
#define IDC_32BPPTEXTURES               1013
#define IDC_SOUND                       1015
#define IDC_MUSIK                       1016
#define IDC_CHICKEN                     1025
#define IDC_SPIN1                       1026
#define IDC_TREES                       1027
#define IDC_SPIN2                       1028
#define IDC_X                           1029
#define IDC_Z                           1030
#define IDC_INTRO                       1031
#define IDC_STALL                       1033
#define IDC_SPIN3                       1034

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
